  - name: Start VM with QEMU
      run: |
        nohup qemu-system-x86_64 \
          -m 16384 \
          -smp 4 \
          -drive file=ubuntu-22.04.img,if=virtio \
          -drive file=seed.img,if=virtio \
          -net nic -net user,hostfwd=tcp::2222-:22,hostfwd=tcp::8080-:8080,hostfwd=tcp::80-:80,hostfwd=tcp::443-:443 \
          -nographic > vm.log 2>&1 &

    - name: Wait for Boot
      run: sleep 90

    - name: Start SSH Session (tmate)
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
